### PR TITLE
[feat][store] Add scan feature .

### PR DESCRIPTION
**Pull request by yuhaijun999**
1.Increased flexibility of client and server。
 2.The server side has a protection function and will not be occupied by too many resources by one of the scans.
 3.Shut down resources gracefully on a regular basis, which is good for monitoring。
  4.Provide the basis for Co-Processor.

### CODE REVIEW

**Review by ketor — APPROVED** [review]
LGTM

**Review by ketor — CHANGES_REQUESTED** [review]
Request changes

**Comment by yuhaijun999** [comment]
已经改名字了

**Review by ketor — APPROVED** [review]
LGTM

**Pull request merged**
